# Generated by Django 4.2.4 on 2023-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likmname', models.CharField(blank=True, max_length=100, null=True)),
                ('likcname', models.CharField(blank=True, max_length=100, null=True)),
                ('likmusic', models.FileField(blank=True, null=True, upload_to='Music')),
                ('likdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('likimage', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('likusername', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
