# Generated by Django 4.2.4 on 2023-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0004_alter_likedb_likmusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedb',
            name='likmname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='likedb',
            name='likmusic',
            field=models.FileField(blank=True, null=True, upload_to='Music'),
        ),
    ]
