# Generated by Django 4.2.4 on 2023-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0005_alter_likedb_likmname_alter_likedb_likmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraddMusicdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('music', models.FileField(blank=True, null=True, upload_to='Music')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.AlterField(
            model_name='likedb',
            name='likmname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
