# Generated by Django 4.2.4 on 2023-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0008_rename_category_useraddmusicdb_ucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddmusicdb',
            name='uimage',
            field=models.ImageField(blank=True, null=True, upload_to='uImages'),
        ),
        migrations.AlterField(
            model_name='useraddmusicdb',
            name='umusic',
            field=models.FileField(blank=True, null=True, upload_to='uMusic'),
        ),
    ]
