# Generated by Django 4.2.4 on 2023-12-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0009_alter_useraddmusicdb_uimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraddMusicdb',
        ),
    ]
