# Generated by Django 4.2.4 on 2023-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addMusicdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('music', models.ImageField(blank=True, null=True, upload_to='Music')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
