# Generated by Django 4.2.4 on 2023-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmusicdb',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='Music'),
        ),
    ]
