# Generated by Django 4.2.4 on 2023-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_addmusicdb_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
