# Generated by Django 4.2.4 on 2023-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_addcatedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcatedb',
            name='catimage',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
