# Generated by Django 4.2.4 on 2023-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_alter_addcatedb_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='replydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
