# Generated by Django 4.2.4 on 2023-12-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_replydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='addeventdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evename', models.CharField(blank=True, max_length=100, null=True)),
                ('eveplace', models.CharField(blank=True, max_length=100, null=True)),
                ('evedate', models.DateField(blank=True, max_length=100, null=True)),
                ('evedescription', models.CharField(blank=True, max_length=100, null=True)),
                ('eveimage', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('eveorganiser', models.CharField(blank=True, max_length=100, null=True)),
                ('evecontact', models.IntegerField(blank=True, max_length=100, null=True)),
                ('eveguest', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
